### PR TITLE
Add about text to front page

### PR DESCRIPTION
**Pull request by davidmsibley**
image

### CODE REVIEW

**Comment by davidmsibley** [comment]
Or in it's own section:
image

**Comment by schoep** [comment]
I like it in its own section. Now I'm thinking we should pare down the geophysical log description to be closer to Q core, but I'll wait to hear from Linda.

**Comment by davidmsibley** [comment]
consolidated, without description:
image

**Comment by davidmsibley** [comment]
Another option: hybrid section, default closed
image

and opened:
image

**Pull request merged**
